# Dependabot configuration for GitHub Actions and npm (pnpm)
version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'security'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      actions:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    rebase-strategy: 'auto'
    ignore:
      - dependency-name: 'actions/setup-node'
        update-types: ['version-update:semver-major']
    assignees:
      - broadsage/developers
    reviewers:
      - broadsage/developers
    versioning-strategy: increase
  # Enable version updates for npm (pnpm)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
    groups:
      tailwind:
        patterns:
          - 'tailwindcss'
          - 'autoprefixer'
          - 'postcss'
      nuxt:
        patterns:
          - 'nuxt'
          - '@nuxt/*'
      vue:
        patterns:
          - 'vue*'
      linting:
        patterns:
          - 'eslint*'
          - 'prettier*'
      typescript:
        patterns:
          - 'typescript'
    allow:
      - dependency-type: 'all'
    rebase-strategy: 'auto'
    ignore:
      - dependency-name: 'nuxt'
        update-types: ['version-update:semver-major']
    assignees:
      - broadsage/developers
    reviewers:
      - broadsage/developers
    versioning-strategy: increase
    # Optionally, you can add more settings like assignees, reviewers, etc.
    # assignees:
    #   - your-github-username
    # reviewers:
    #   - your-github-username
