name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Node Prepare Job
        uses: ./.github/actions/node-prepare/action.yaml
        with:
          job-name: Lint
          run-script: lint
          artifact-name: lint-results
          artifact-path: .eslint* .pnpm-debug.log