name: Typecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: typecheck-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Node Prepare Job
        uses: ./.github/actions/node-prepare
        with:
          job-name: Typecheck
          run-script: typecheck
          artifact-name: typecheck-results
          artifact-path: .typecheck* .pnpm-debug.log